name: 'ESP-IDF Size Delta'
description: 'Build ESP-IDF app and report FLASH and RAM deltas vs a base ref'
author: 'espp'

inputs:
  app_name:
    description: 'Name of the ESP-IDF app (for reporting)'
    required: true
  app_path:
    description: 'Relative path to the ESP-IDF app (contains CMakeLists.txt)'
    required: true
  idf_version:
    description: 'ESP-IDF version to setup'
    required: false
    default: 'v5.5'
  idf_target:
    description: 'ESP-IDF target (defaults to IDF_TARGET env var or "esp32")'
    required: false
  idf_component_manager:
    description: 'Set IDF_COMPONENT_MANAGER ("0" to disable)'
    required: false
    default: '0'
  base_ref:
    description: 'Git ref/sha to use as base for delta (defaults to PR base sha)'
    required: false
  post_comment:
    description: 'Whether to post a PR comment (true/false)'
    required: false
    default: 'true'
  flash_total_override:
    description: 'Override total FLASH bytes for percentage (optional)'
    required: false
    default: ''
  github_token:
    description: 'GitHub token'
    required: false
    default: ${{ github.token }}
  checkout_token:
    description: 'Token to use for checkout actions (defaults to GITHUB_TOKEN)'
    required: false
    default: ''

outputs:
  markdown:
    description: 'Markdown report for this app'
    value: ${{ steps.mkdown.outputs.markdown }}

runs:
  using: 'composite'
  steps:
    - name: Set up Python
      uses: actions/setup-python@v5
      id: id_python_313
      with:
        python-version: '3.13'

    - name: Checkout HEAD
      uses: actions/checkout@v5
      with:
        submodules: 'recursive'
        token: ${{ inputs.checkout_token || github.token }}
        path: head
        fetch-depth: 0

    - name: Build (HEAD)
      uses: espressif/esp-idf-ci-action@v1
      with:
        esp_idf_version: ${{ inputs.idf_version }}
        target: ${{ inputs.idf_target }}
        path: head/${{ inputs.app_path }}
        command: |
          set IDF_COMPONENT_MANAGER=${{ inputs.idf_component_manager }}
          idf.py size --format json2 --output-file idf_size.json

    - name: Process size (HEAD)
      shell: bash
      working-directory: head/${{ inputs.app_path }}
      run:
        python ${{ github.action_path }}/idf_size_report.py --in-file idf_size.json --out-file size.json --flash-total-override "${{ inputs.flash_total_override }}" || echo '{"flash":0,"dram":0,"iram":0,"ram":0}' > size.json

    - name: Checkout BASE
      uses: actions/checkout@v5
      with:
        ref: ${{ inputs.base_ref != '' && inputs.base_ref || github.event.pull_request.base.sha }}
        submodules: 'recursive'
        token: ${{ inputs.checkout_token || github.token }}
        path: base
        fetch-depth: 0

    - name: Build (BASE)
      uses: espressif/esp-idf-ci-action@v1
      with:
        esp_idf_version: ${{ inputs.idf_version }}
        target: ${{ inputs.idf_target }}
        path: base/${{ inputs.app_path }}
        command: |
          set IDF_COMPONENT_MANAGER=${{ inputs.idf_component_manager }}
          idf.py size --format json2 --output-file idf_size.json

    - name: Process size (BASE)
      shell: bash
      working-directory: base/${{ inputs.app_path }}
      run:
        python ${{ github.action_path }}/idf_size_report.py --in-file idf_size.json --out-file size.json --flash-total-override "${{ inputs.flash_total_override }}" || echo '{"flash":0,"dram":0,"iram":0,"ram":0}' > size.json

    - name: Make markdown
      id: mkdown
      shell: bash
      run: |
        # generate markdown
        md=$(${{ steps.id_python_313.outputs.python-path }} ${{ github.action_path }}/render_markdown.py --app-name "${{ inputs.app_name }}" --head-json head/${{ inputs.app_path }}/size.json --base-json base/${{ inputs.app_path }}/size.json)
        # append to summary and set output
        echo "$md" >> "$GITHUB_STEP_SUMMARY"
        echo "markdown<<EOF" >> $GITHUB_OUTPUT
        echo "$md" >> $GITHUB_OUTPUT
        echo "EOF" >> $GITHUB_OUTPUT

    - name: Comment on PR
      if: ${{ inputs.post_comment == 'true' && github.event_name == 'pull_request' }}
      uses: actions/github-script@v7
      with:
        github-token: ${{ inputs.github_token }}
        script: |
          const body = `${{ steps.mkdown.outputs.markdown }}`
          const {owner, repo, number} = context.issue;
          const appName = `${{ inputs.app_name }}`;
          const commentIdentifier = `<!-- esp-idf-size-delta:${appName} -->`;
          
          // Get existing comments
          const comments = await github.rest.issues.listComments({
            owner,
            repo,
            issue_number: number,
          });
          
          // Find existing comment with our identifier
          const existingComment = comments.data.find(comment => 
            comment.body && comment.body.includes(commentIdentifier)
          );
          
          if (existingComment) {
            // Update existing comment
            await github.rest.issues.updateComment({
              owner,
              repo,
              comment_id: existingComment.id,
              body
            });
            console.log(`Updated existing comment ${existingComment.id}`);
          } else {
            // Create new comment
            await github.rest.issues.createComment({
              owner,
              repo,
              issue_number: number,
              body
            });
            console.log('Created new comment');
          }

    - name: Append to Release Notes (if Release)
      if: ${{ github.event.release && github.event.action == 'published' }}
      uses: actions/github-script@v7
      with:
        github-token: ${{ inputs.github_token }}
        script: |
          const addition = `${{ steps.mkdown.outputs.markdown }}`
          const {owner, repo} = context.repo;
          const release_id = context.payload.release.id;
          const current = context.payload.release.body || '';
          const body = [current, '', addition].filter(Boolean).join('\n');
          await github.rest.repos.updateRelease({ owner, repo, release_id, body });
